### ISSUE TITLE
Why reduceRight?

### ISSUE THREAD

**Issue by Dalfons0** [mtraynham/lodash-joins#8]
Hello,
First of all I want to give my congratulations for your amazing work in the module, the functionality coverage it's great, but there is something that intrigue me, and is why do you use reduceRight instead of reduce? there is some efficiency concepts that I am missing? because the [lodash](https://lodash.com/docs/4.17.4#reduceRight) documentation say the following:

> This method is like _.reduce except that it iterates over elements of collection from right to left.

Thanks in advance for satisfying my curiosity :)

**Comment by mtraynham** [comment]
Ha, that is very flattering and much appreciated.

`reduceRight`, yeah, so this mostly comes from a "potential" performance increase using a `while` loop in reverse.  The reason I say "potential", there's really no definitive evidence this is actually an optimization, especially with the wide-range of browsers and JavaScript implementations.  

I'll explain.

Lodash's implementation of [reduce](https://github.com/lodash/lodash/blob/6cb3460fcefe66cb96e55b82c6febd2153c992cc/reduce.js#L1) depends on a seperate function that actually does the iteration called [arrayReduce](https://github.com/lodash/lodash/blob/6cb3460fcefe66cb96e55b82c6febd2153c992cc/.internal/arrayReduce.js).  It has a `while` loop that looks like this, which iterates over the array:

```js
  while (++index < length) {
    accumulator = iteratee(accumulator, array[index], index, array)
  }
```

Alternatively, [reduceRight](https://github.com/lodash/lodash/blob/6cb3460fcefe66cb96e55b82c6febd2153c992cc/reduceRight.js) depends on a function called [arrayReduceRight](https://github.com/lodash/lodash/blob/6cb3460fcefe66cb96e55b82c6febd2153c992cc/.internal/arrayReduceRight.js).  It also has a `while` loop that looks like this:

```js
  while (length--) {
    accumulator = iteratee(accumulator, array[length], length, array)
  }
```

The performance gain comes from the `while`'s conditional.  The `arrayReduce` implementation uses a while loop that has to perform a less-than comparison every iteration to check if the current `index` is less than the `length`.  The `arrayReduceRight` does not need the comparison, because it will decrement the variable until it hits 0 and because 0 is falsy in JavaScript, it will end the loop.

This has been pretty widely discussed elsewhere, so maybe some of these links will be of interest to you.

http://stackoverflow.com/a/1340634
http://stackoverflow.com/questions/3520688/javascript-loop-performance-why-is-to-decrement-the-iterator-toward-0-faster-t
http://stackoverflow.com/a/25047179

**Comment by Dalfons0** [comment]
Really good feedback. Thank you!!!
